nelmio_api_doc:
    documentation:
        info:
            title: homeAssignment20240403
            description: homeAssignment20240403 api doc
            version: 1.0.0
        servers:
            - url: http://127.0.0.1:3003
              description: API dev path
    areas:
        path_patterns:
            - ^\/api(?!\/doc(\.json)?$)