version: "3"

services:
    mysql:
        container_name: ${PROJECT_NAME}_mysql
        restart: unless-stopped
        image: ${MYSQL_IMAGE}
        ports:
            - "${MYSQL_PORT}:3306"
        volumes:
            - ./mysql/my.cnf:/etc/mysql/my.cnf
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        networks:
            - symfony_app
    messenger_consumer:
        container_name: ${PROJECT_NAME}_messenger_consumer
        restart: unless-stopped
        env_file:
            - .env
        build:
            context: ./php
            args:
                TIMEZONE: ${TIMEZONE}
                PHP_IMAGE: ${PHP_IMAGE}
        volumes:
            - ../backend/:/var/www/symfony:cached
            - .env:/var/www/symfony/.env
        networks:
            - symfony_app
        command: /bin/sh -c "php bin/console messenger:consume -vv transactions failed_transactions"
    redis:
        image: ${REDIS_IMAGE}
        container_name: ${PROJECT_NAME}_redis
        ports:
            - "${REDIS_PORT}:6379"
        networks:
            - symfony_app
    php:
        container_name: ${PROJECT_NAME}_php
        restart: unless-stopped
        env_file:
            - .env
        build:
            context: ./php
            args:
                TIMEZONE: ${TIMEZONE}
                PHP_IMAGE: ${PHP_IMAGE}
        volumes:
            - ../backend/:/var/www/symfony:cached
            - .env:/var/www/symfony/.env
        networks:
            - symfony_app
    nginx:
        container_name: ${PROJECT_NAME}_nginx
        restart: unless-stopped
        build:
            context: ./nginx
            args:
                NGINX_IMAGE: ${NGINX_IMAGE}
        volumes:
            - ../backend/:/var/www/symfony
        ports:
            - "${NGINX_PORT}:80"
        networks:
            - symfony_app

networks:
    symfony_app:
        driver: bridge
